#!/bin/sh

# 修改LAN接口的IP
sed -i "s/192.168.31.1/192.168.3.108/g" package/base-files/files/bin/config_generate


# 设置系统管理密码为root
echo -e "root\nroot" | passwd

# 主题设置
sed -i 's/bing/none/' package/openwrt-pacmluci-app-argon-config/root/etc/config/argon

# 提交并应用配置
uci commit network
/etc/init.d/network restart
/etc/init.d/system restart


exit 0
