#!/bin/sh

# 修改LAN接口的IP
uci set network.lan.ipaddr='192.168.2.158'

# 修改LAN接口的网关为192.168.0.1
uci set network.lan.gateway='192.168.2.1'

# 修改LAN接口的DNS为223.5.5.5
#uci set network.lan.dns='223.5.5.5'


# 设置系统管理密码为root
echo -e "root\nroot" | passwd

# 主题设置
sed -i 's/bing/none/' package/openwrt-pacmluci-app-argon-config/root/etc/config/argon



echo "All done!"
