#!/bin/sh

# 修改LAN接口的IP
uci set network.lan.ipaddr='192.168.3.108'

# 修改LAN接口的网关为192.168.0.1
uci set network.lan.gateway='192.168.3.1'

# 修改LAN接口的DNS为223.5.5.5
uci set network.lan.dns='223.5.5.5'


# 设置系统管理密码为root
echo -e "root\nroot" | passwd

# 提交并应用配置
uci commit network
/etc/init.d/network restart
/etc/init.d/system restart

# 加载软件源
git clone --depth=1 https://github.com/oppen321/openwrt-package package/openwrt-package

# 添加第三方应用
mkdir kiddin9
pushd kiddin9
git clone --depth=1 https://github.com/kiddin9/kwrt-packages .
popd

# update feeds
./scripts/feeds update -a
./scripts/feeds install -a

exit 0
