#!/bin/sh

# 修改LAN接口的IP
uci set network.lan.ipaddr='192.168.0.11'

# 修改LAN接口的网关为192.168.0.1
uci set network.lan.gateway='192.168.2.158'

# 修改LAN接口的DNS为223.5.5.5
uci set network.lan.dns='223.5.5.5'


# 设置系统管理密码为root
echo -e "root\nroot" | passwd

# 提交并应用配置
uci commit network
/etc/init.d/network restart
/etc/init.d/system restart

exit 0
