name: Armbian x86

on:
  workflow_dispatch:
    inputs:
      upload_artifacts:
        description: '上传固件'
        required: true
        default: 'false'
        type: boolean
      upload_release:
        description: '上传到Release'
        required: true
        default: 'true'
        type: boolean

jobs:
  build:
    runs-on: ubuntu-22.04

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set variables
        run: |
          if [[ "${{ github.event.inputs.upload_artifacts }}" == 'true' ]]; then
            echo "UPLOAD_ARTIFACTS=true" >> $GITHUB_ENV
          else
            echo "UPLOAD_ARTIFACTS=false" >> $GITHUB_ENV
          fi
          if [[ "${{ github.event.inputs.upload_release }}" == 'true' ]]; then
            echo "UPLOAD_RELEASE=true" >> $GITHUB_ENV
          else
            echo "UPLOAD_RELEASE=false" >> $GITHUB_ENV
          fi

      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y git build-essential debootstrap

      - name: Build Armbian
        run: |
          git clone --depth=1 --branch=main https://github.com/armbian/build.git build 
          cd build
          ./compile.sh \
          BOARD=uefi-x86 \
          BRANCH=edge \
          RELEASE=noble \
          BUILD_MINIMAL=yes \
          BUILD_DESKTOP=no \
          KERNEL_CONFIGURE=no
          sudo chown $(id -u):$(id -g) -R output/

      

      - name: Hash and compress images
        run: |
          for f in ./build/output/images/*.img; do
            sha256sum "$f" | tee -a sha256sum
            xz --threads=0 --compress "$f"
          done

      - name: Create Release Tag
        if: env.UPLOAD_RELEASE == 'true'
        run: |
          echo "release_tag=$(date +%Y%m%d)" >> $GITHUB_ENV

      - name: Upload artifacts
        if: env.UPLOAD_ARTIFACTS == 'true'
        uses: actions/upload-artifact@main
        with:
          name: armbian-image
          path: ./build/output/images/*.xz

      - name: Upload to release
        if: env.UPLOAD_RELEASE == 'true'
        uses: softprops/action-gh-release@v2.1.0
        with:
          tag_name: ${{ env.release_tag }}
          name: Armbian ${{ env.release_tag }}
          files: ./build/output/images/*.xz
